name: publish

on:
  schedule:
    - cron: '51 4 * * *'
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Run Publish
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements
          python ./post.py
